# Generated by Django 4.1.7 on 2023-03-25 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0002_alter_sentemail_sent_by_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentemail',
            name='sent_by_email_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to=settings.AUTH_USER_MODEL),
        ),
    ]
