# Generated by Django 4.1.7 on 2023-03-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_alter_sentemail_sent_by_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentemail',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
