# Generated by Django 4.1.7 on 2023-03-25 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_alter_sentemail_body_alter_sentemail_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
