# Generated by Django 4.1.7 on 2023-03-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_emailtemplate_created_emailtemplate_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sentemail',
            name='recipient_email_addresses',
        ),
        migrations.AddField(
            model_name='sentemail',
            name='recipients',
            field=models.ManyToManyField(related_name='received_emails', to='emails.recipient'),
        ),
    ]
